[package]
name = "photon_correlation"
version = "0.1.0"
authors = ["Greg Morenz <morenzg@gmail.com>"]
edition = "2018"

[dependencies]
nom = { version="4.1.1", features=["verbose-errors"] }
memmap = "0.7.0"
arrayref = "0.3.5"
structopt = "0.2.14"
crossbeam-utils = "0.6.3"
